version: '3.5'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: maramax
    ports:
      - 5432:5432